// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"
#include "ui_helpers.h"
#include <stdbool.h>

extern bool TRIGGER_RESTART;

extern bool SELECT_NEXT_PAGE;
extern bool SELECT_PREV_PAGE;

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenConnection
void ui_ScreenConnection_screen_init(void);
lv_obj_t * ui_ScreenConnection;
lv_obj_t * ui_waitBg;
void ui_event_btnHome3(lv_event_t * e);
lv_obj_t * ui_btnHome3;
lv_obj_t * ui_connectionLabel;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenInfo
void ui_ScreenInfo_screen_init(void);
lv_obj_t * ui_ScreenInfo;
void ui_event_btnHome(lv_event_t * e);
lv_obj_t * ui_btnHome;
lv_obj_t * ui_fwVersion;
lv_obj_t * ui_screenId;
void ui_event_alwaysOn(lv_event_t * e);
lv_obj_t * ui_alwaysOn;
lv_obj_t * ui_Label7;
void ui_event_btnRestart(lv_event_t * e);
lv_obj_t * ui_btnRestart;
lv_obj_t * ui_infoBg;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
lv_obj_t * ui_ScreenSetting;
lv_obj_t * ui_settingBg;
void ui_event_btnHome1(lv_event_t * e);
lv_obj_t * ui_btnHome1;
void ui_event_Arc1(lv_event_t * e);
lv_obj_t * ui_Arc1;
lv_obj_t * ui_setPointNum;
lv_obj_t * ui_regLabel;
lv_obj_t * ui_tempInPage;
lv_obj_t * ui_labelTempInPage;
lv_obj_t * ui_debugLabel;
// CUSTOM VARIABLES


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_homeBg;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_labelBtn1;
lv_obj_t * ui_labelBtn2;
lv_obj_t * ui_labelBtn3;
lv_obj_t * ui_labelBtn4;
lv_obj_t * ui_labelBtn5;
lv_obj_t * ui_labelBtn6;
lv_obj_t * ui_labelBtn7;
lv_obj_t * ui_labelBtn8;
lv_obj_t * ui_labelBtn9;
lv_obj_t * ui_labelBtn10;
lv_obj_t * ui_labelBtn11;
lv_obj_t * ui_labeBtn12;
lv_obj_t * ui_ledBtn1;
lv_obj_t * ui_ledBtn2;
lv_obj_t * ui_ledBtn3;
lv_obj_t * ui_ledBtn4;
lv_obj_t * ui_ledBtn5;
lv_obj_t * ui_ledBtn6;
lv_obj_t * ui_ledBtn7;
lv_obj_t * ui_ledBtn8;
lv_obj_t * ui_ledBtn9;
lv_obj_t * ui_ledBtn10;
lv_obj_t * ui_ledBtn11;
lv_obj_t * ui_ledBtn12;
lv_obj_t * ui_tempLabel1;
lv_obj_t * ui_tempLabel2;
lv_obj_t * ui_tempLabel3;
lv_obj_t * ui_tempLabel4;
lv_obj_t * ui_tempLabel5;
lv_obj_t * ui_tempLabel6;
lv_obj_t * ui_tempLabel7;
lv_obj_t * ui_tempLabel8;
lv_obj_t * ui_tempLabel9;
lv_obj_t * ui_tempLabel10;
lv_obj_t * ui_tempLabel11;
lv_obj_t * ui_tempLabel12;
void ui_event_btnInfo(lv_event_t * e);
lv_obj_t * ui_btnInfo;
void ui_event_btnPrevPage(lv_event_t * e);
lv_obj_t * ui_btnPrevPage;
void ui_event_btnNextPage(lv_event_t * e);
lv_obj_t * ui_btnNextPage;
lv_obj_t * ui_Label2;
lv_obj_t * ui_labelPageNum;
// CUSTOM VARIABLES


// SCREEN: ui_BlackScreen
void ui_BlackScreen_screen_init(void);
void ui_event_BlackScreen(lv_event_t * e);
lv_obj_t * ui_BlackScreen;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenView
void ui_ScreenView_screen_init(void);
lv_obj_t * ui_ScreenView;
void ui_event_btnHome4(lv_event_t * e);
lv_obj_t * ui_btnHome4;
lv_obj_t * ui_viewTempValue;
lv_obj_t * ui_labelViewTemp;
lv_obj_t * ui_debugLabel1;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenBoolControl
void ui_ScreenBoolControl_screen_init(void);
lv_obj_t * ui_ScreenBoolControl;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_labelBoolControl;
lv_obj_t * ui_labelONOFF;
void ui_event_btnHome5(lv_event_t * e);
lv_obj_t * ui_btnHome5;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
lv_obj_t * ui_labelBtn12;
lv_obj_t * ui_labelBtn13;
lv_obj_t * ui_labelBtn14;
lv_obj_t * ui_labelBtn15;
lv_obj_t * ui_labelBtn16;
lv_obj_t * ui_labelBtn17;
lv_obj_t * ui_labelBtn18;
lv_obj_t * ui_labelBtn19;
lv_obj_t * ui_labelBtn20;
lv_obj_t * ui_labelBtn21;
lv_obj_t * ui_labelBtn22;
lv_obj_t * ui_labeBtn1;
void ui_event_btnInfo1(lv_event_t * e);
lv_obj_t * ui_btnInfo1;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnHome3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_btnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_alwaysOn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        saveAOtoSD(e);
    }
}

void ui_event_btnRestart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TRIGGER_RESTART = true;
    }
}

void ui_event_btnHome1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        knobValueRead(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        knobReleased(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB1(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB2(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB3(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB4(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB5(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB6(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB7(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB8(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB9(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB10(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB11(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB12(e);
    }
}

void ui_event_btnInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenInfo, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_ScreenInfo_screen_init);
    }
}

void ui_event_btnPrevPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SELECT_PREV_PAGE = true;
    }
}

void ui_event_btnNextPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SELECT_NEXT_PAGE = true;
    }
}

void ui_event_BlackScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 1, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_btnHome4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        pulsanteControlloRemoto(e);
        (e);
    }
}

void ui_event_btnHome5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_OVER_RIGHT, 200, 0, &ui_ScreenSetting_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        eventoB1(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB2(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB3(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB4(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB5(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB6(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB7(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB8(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB9(e);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB10(e);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB11(e);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        eventoB12(e);
    }
}

void ui_event_btnInfo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenInfo, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_ScreenInfo_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_img_pulsante_home_png_load();
    ui_img_btn_info_png_load();
    ui_ScreenConnection_screen_init();
    ui_ScreenInfo_screen_init();
    ui_ScreenSetting_screen_init();
    ui_Screen1_screen_init();
    ui_BlackScreen_screen_init();
    ui_ScreenView_screen_init();
    ui_ScreenBoolControl_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenConnection);
}
