// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#ifndef _SOLARIA_BASIC_APP_UI_H
#define _SOLARIA_BASIC_APP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

#include "ui_img_manager.h"

// SCREEN: ui_ScreenConnection
void ui_ScreenConnection_screen_init(void);
extern lv_obj_t * ui_ScreenConnection;
extern lv_obj_t * ui_waitBg;
void ui_event_btnHome3(lv_event_t * e);
extern lv_obj_t * ui_btnHome3;
extern lv_obj_t * ui_connectionLabel;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenInfo
void ui_ScreenInfo_screen_init(void);
extern lv_obj_t * ui_ScreenInfo;
void ui_event_btnHome(lv_event_t * e);
extern lv_obj_t * ui_btnHome;
extern lv_obj_t * ui_fwVersion;
extern lv_obj_t * ui_screenId;
void ui_event_alwaysOn(lv_event_t * e);
extern lv_obj_t * ui_alwaysOn;
extern lv_obj_t * ui_Label7;
void ui_event_btnRestart(lv_event_t * e);
extern lv_obj_t * ui_btnRestart;
extern lv_obj_t * ui_infoBg;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
extern lv_obj_t * ui_ScreenSetting;
extern lv_obj_t * ui_settingBg;
void ui_event_btnHome1(lv_event_t * e);
extern lv_obj_t * ui_btnHome1;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_setPointNum;
extern lv_obj_t * ui_regLabel;
extern lv_obj_t * ui_tempInPage;
extern lv_obj_t * ui_labelTempInPage;
extern lv_obj_t * ui_debugLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_homeBg;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_labelBtn1;
extern lv_obj_t * ui_labelBtn2;
extern lv_obj_t * ui_labelBtn3;
extern lv_obj_t * ui_labelBtn4;
extern lv_obj_t * ui_labelBtn5;
extern lv_obj_t * ui_labelBtn6;
extern lv_obj_t * ui_labelBtn7;
extern lv_obj_t * ui_labelBtn8;
extern lv_obj_t * ui_labelBtn9;
extern lv_obj_t * ui_labelBtn10;
extern lv_obj_t * ui_labelBtn11;
extern lv_obj_t * ui_labeBtn12;
extern lv_obj_t * ui_ledBtn1;
extern lv_obj_t * ui_ledBtn2;
extern lv_obj_t * ui_ledBtn3;
extern lv_obj_t * ui_ledBtn4;
extern lv_obj_t * ui_ledBtn5;
extern lv_obj_t * ui_ledBtn6;
extern lv_obj_t * ui_ledBtn7;
extern lv_obj_t * ui_ledBtn8;
extern lv_obj_t * ui_ledBtn9;
extern lv_obj_t * ui_ledBtn10;
extern lv_obj_t * ui_ledBtn11;
extern lv_obj_t * ui_ledBtn12;
extern lv_obj_t * ui_tempLabel1;
extern lv_obj_t * ui_tempLabel2;
extern lv_obj_t * ui_tempLabel3;
extern lv_obj_t * ui_tempLabel4;
extern lv_obj_t * ui_tempLabel5;
extern lv_obj_t * ui_tempLabel6;
extern lv_obj_t * ui_tempLabel7;
extern lv_obj_t * ui_tempLabel8;
extern lv_obj_t * ui_tempLabel9;
extern lv_obj_t * ui_tempLabel10;
extern lv_obj_t * ui_tempLabel11;
extern lv_obj_t * ui_tempLabel12;
void ui_event_btnInfo(lv_event_t * e);
extern lv_obj_t * ui_btnInfo;
void ui_event_btnPrevPage(lv_event_t * e);
extern lv_obj_t * ui_btnPrevPage;
void ui_event_btnNextPage(lv_event_t * e);
extern lv_obj_t * ui_btnNextPage;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_labelPageNum;
// CUSTOM VARIABLES

// SCREEN: ui_BlackScreen
void ui_BlackScreen_screen_init(void);
void ui_event_BlackScreen(lv_event_t * e);
extern lv_obj_t * ui_BlackScreen;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenView
void ui_ScreenView_screen_init(void);
extern lv_obj_t * ui_ScreenView;
void ui_event_btnHome4(lv_event_t * e);
extern lv_obj_t * ui_btnHome4;
extern lv_obj_t * ui_viewTempValue;
extern lv_obj_t * ui_labelViewTemp;
extern lv_obj_t * ui_debugLabel1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenBoolControl
void ui_ScreenBoolControl_screen_init(void);
extern lv_obj_t * ui_ScreenBoolControl;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_labelBoolControl;
extern lv_obj_t * ui_labelONOFF;
void ui_event_btnHome5(lv_event_t * e);
extern lv_obj_t * ui_btnHome5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_labelBtn12;
extern lv_obj_t * ui_labelBtn13;
extern lv_obj_t * ui_labelBtn14;
extern lv_obj_t * ui_labelBtn15;
extern lv_obj_t * ui_labelBtn16;
extern lv_obj_t * ui_labelBtn17;
extern lv_obj_t * ui_labelBtn18;
extern lv_obj_t * ui_labelBtn19;
extern lv_obj_t * ui_labelBtn20;
extern lv_obj_t * ui_labelBtn21;
extern lv_obj_t * ui_labelBtn22;
extern lv_obj_t * ui_labeBtn1;
void ui_event_btnInfo1(lv_event_t * e);
extern lv_obj_t * ui_btnInfo1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_pulsante_home_png;   // assets/pulsante_home.png
void ui_img_pulsante_home_png_load();
extern lv_img_dsc_t ui_img_btn_info_png;   // assets/btn_info.png
void ui_img_btn_info_png_load();

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
