// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void saveAOtoSD(lv_event_t * e);
void knobValueRead(lv_event_t * e);
void knobReleased(lv_event_t * e);
void eventoB1(lv_event_t * e);
void eventoB2(lv_event_t * e);
void eventoB3(lv_event_t * e);
void eventoB4(lv_event_t * e);
void eventoB5(lv_event_t * e);
void eventoB6(lv_event_t * e);
void eventoB7(lv_event_t * e);
void eventoB8(lv_event_t * e);
void eventoB9(lv_event_t * e);
void eventoB10(lv_event_t * e);
void eventoB11(lv_event_t * e);
void eventoB12(lv_event_t * e);
void pulsanteControlloRemoto(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
