// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"
#include "../../include/main.h"
#include "../../include/display_helpers.h"
#include <string.h>
#include <Arduino.h>

extern TYPE_BTN_PRESSED tButton;
extern bool SETPOINT_CHANGED;
extern float newSetPoint[MAX_LABELS];
extern long azzera_counter;
extern bool BTN_ALWAYS_ON;
extern unsigned long arcLastTouchTime;
extern unsigned long switchLastTouchTime;
extern int valueChanged[MAX_LABELS];

void eventoB1(lv_event_t *e)
{
	// Your code here

	tButton = STATO_BTN1;
	HANDLE_BUTTON = true;
}

void eventoB2(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN2;
}

void eventoB3(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN3;
}

void eventoB4(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN4;
}

void eventoB5(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN5;
}

void eventoB6(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN6;
}

void eventoB7(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN7;
}

void eventoB9(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN9;
}

void eventoB10(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN10;
}

void eventoB11(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN11;
}

void eventoB12(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN12;
}

void eventoB8(lv_event_t *e)
{
	// Your code here
	//_ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSetting_screen_init);
	HANDLE_BUTTON = true;
	tButton = STATO_BTN8;
}

void arcChanged(lv_event_t *e)
{
	// Your code here
	arcSetpoint = lv_arc_get_value(ui_Arc1);
}

/******************keyboard ****************** */
// Force-bind the keyboard to the text area after UI is created

static void pin_value_changed(lv_event_t *e)
{
	lv_obj_t *ta = lv_event_get_target(e);
	const char *txt = lv_textarea_get_text(ta);

	// Quick visual feedback: auto-clear if > 8 chars so you can keep testing
	if (strlen(txt) > 8)
		lv_textarea_set_text(ta, "");

	// Navigate on 1111 (auto as soon as you type it)
	if (strlen(txt) == 4)
	{
		if (strcmp(txt, "1111") == 0)
		{
			_ui_screen_change(&ui_ScreenInfo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenInfo_screen_init);
		}
		else
		{
			lv_textarea_set_text(ta, "");
		}
	}
}

/*********************************************** */
// Fired when the user presses the "OK/✓" key on the keyboard
void check_code(lv_event_t *e)
{
	lv_obj_t *ta = lv_event_get_target(e); // ui_PasswText
	const char *txt = lv_textarea_get_text(ta);

	if (strcmp(txt, "1111") == 0)
	{
		// Navigate: use the correct screen symbol from ui.h
		// Instant:
		// lv_disp_load_scr(ui_ScreenInfo);

		// Animated (matches your other buttons):
		//_ui_screen_change(&ui_ScreenId, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenId_screen_init);
	}
	else
	{
		lv_textarea_set_text(ta, "");
	}
}

/**
 * funzione eseguita ogni volta che il valore del knob cambia
 */
void knobValueRead(lv_event_t *e)
{
	arcLastTouchTime = millis();

	// flag cambiamento
	SETPOINT_CHANGED = true;
	lv_label_set_text(ui_debugLabel, "chg");
	// Define the global label object generated by SquareLine Studio
	extern lv_obj_t *ui_setPointNum;

	lv_obj_t *obj = lv_event_get_target(e);
	int32_t current_value = lv_arc_get_value(obj);

	// --- 1. Rounding to Nearest 0.5 (or nearest multiple of 5 in raw integer) ---

	int32_t remainder = current_value % 5;

	// Adjust the raw value to the nearest multiple of 5 (rounding logic)
	if (remainder != 0)
	{
		if (abs(remainder) >= 3)
		{
			// Round up/down toward the nearest multiple of 5
			current_value += (current_value > 0) ? (5 - remainder) : (-5 - remainder);
		}
		else
		{
			// Round down/up toward zero
			current_value -= remainder;
		}
	}

	// --- 2. Formatting to X.Y Decimal String with Unit ---

	int32_t wholePart = current_value / 10;
	int8_t decimalDigit = abs(current_value % 10);

	// Define buffer. Needs to be larger to hold the unit (e.g., "-100.0 °C\0" needs ~10 chars)
	char buffer[16];

	// Format: Long integer (. ), Integer, followed by the literal string " °C"
	snprintf(buffer, sizeof(buffer), "%ld.%d °C", wholePart, decimalDigit);

	// 3. Update the LVGL Label
	if (ui_setPointNum != NULL)
	{
		lv_label_set_text(ui_setPointNum, buffer);
	}
}
void knobReleased(lv_event_t *e)
{
	azzera_counter = millis();
	uint16_t valuez = lv_arc_get_value(ui_Arc1);
	float valuezz = ((valuez / 10.0f) * 10.0f) / 10.0f;
	display_confirm_setpoint(tButton, valuezz);
	lv_label_set_text_fmt(ui_debugLabel, "%d", tButton);
}

void saveAOtoSD(lv_event_t *e)
{
	// Your code here
	BTN_ALWAYS_ON = 1;
}

void pulsanteControlloRemoto(lv_event_t *e)
{
	switchLastTouchTime = lv_tick_get();
	bool is_on = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	float newVal = is_on ? (float)display_get_max(tButton) : (float)display_get_min(tButton);
	newSetPoint[tButton] = newVal;
	display_set_setpoint(tButton, newVal);
	valueChanged[tButton] = 1;
	lv_label_set_text(ui_labelONOFF, is_on ? "ON" : "OFF");
}
