// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

// IMAGE DATA: assets/pulsante_home.png
lv_img_dsc_t ui_img_pulsante_home_png = {
    .header.always_zero = 0,
    .header.w = 0,
    .header.h = 0,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data_size = 0,
    .data = NULL,
};

void ui_img_pulsante_home_png_load()
{
    UI_LOAD_IMAGE("S:assets/ui_img_pulsante_home_png.bin", &ui_img_pulsante_home_png);
}
