// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_ScreenInfo_screen_init(void)
{
    ui_ScreenInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_infoBg = lv_img_create(ui_ScreenInfo);
    lv_obj_set_align(ui_infoBg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_infoBg, 0);
    lv_obj_set_y(ui_infoBg, 0);
    lv_obj_clear_flag(ui_infoBg, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_infoBg, LV_OBJ_FLAG_HIDDEN);

    ui_btnHome = lv_btn_create(ui_ScreenInfo);
    lv_obj_set_width(ui_btnHome, 144);
    lv_obj_set_height(ui_btnHome, 60);
    lv_obj_set_x(ui_btnHome, 0);
    lv_obj_set_y(ui_btnHome, -26);
    lv_obj_set_align(ui_btnHome, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnHome, &ui_img_pulsante_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwVersion = lv_label_create(ui_ScreenInfo);
    lv_obj_set_width(ui_fwVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fwVersion, 1);
    lv_obj_set_y(ui_fwVersion, -54);
    lv_obj_set_align(ui_fwVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwVersion, "FW 1.0.0");
    lv_obj_set_style_text_font(ui_fwVersion, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenId = lv_label_create(ui_ScreenInfo);
    lv_obj_set_width(ui_screenId, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screenId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_screenId, -2);
    lv_obj_set_y(ui_screenId, -25);
    lv_obj_set_align(ui_screenId, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screenId, "id:999");
    lv_obj_set_style_text_font(ui_screenId, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alwaysOn = lv_switch_create(ui_ScreenInfo);
    lv_obj_set_width(ui_alwaysOn, 50);
    lv_obj_set_height(ui_alwaysOn, 25);
    lv_obj_set_x(ui_alwaysOn, 4);
    lv_obj_set_y(ui_alwaysOn, 66);
    lv_obj_set_align(ui_alwaysOn, LV_ALIGN_CENTER);


    ui_Label7 = lv_label_create(ui_ScreenInfo);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 76);
    lv_obj_set_y(ui_Label7, 66);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Always ON");

    ui_btnRestart = lv_btn_create(ui_ScreenInfo);
    lv_obj_set_width(ui_btnRestart, 110);
    lv_obj_set_height(ui_btnRestart, 44);
    lv_obj_set_x(ui_btnRestart, -12);
    lv_obj_set_y(ui_btnRestart, 10);
    lv_obj_set_align(ui_btnRestart, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnRestart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnRestart, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRestart, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnRestart, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnRestart, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t * ui_btnRestart_label = lv_label_create(ui_btnRestart);
    lv_label_set_text(ui_btnRestart_label, "Restart");
    lv_obj_set_style_text_font(ui_btnRestart_label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnRestart_label, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(ui_btnRestart_label);

    lv_obj_add_event_cb(ui_btnHome, ui_event_btnHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alwaysOn, ui_event_alwaysOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRestart, ui_event_btnRestart, LV_EVENT_ALL, NULL);
    lv_obj_move_foreground(ui_btnHome);
    lv_obj_move_foreground(ui_alwaysOn);
    lv_obj_move_foreground(ui_Label7);
    lv_obj_move_foreground(ui_btnRestart);
    lv_obj_move_foreground(ui_fwVersion);
    lv_obj_move_foreground(ui_screenId);

}
