// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_ScreenConnection_screen_init(void)
{
    ui_ScreenConnection = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConnection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waitBg = lv_img_create(ui_ScreenConnection);
    lv_obj_set_align(ui_waitBg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_waitBg, 0);
    lv_obj_set_y(ui_waitBg, 0);
    lv_obj_clear_flag(ui_waitBg, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_waitBg, LV_OBJ_FLAG_HIDDEN);

    ui_connectionLabel = lv_label_create(ui_ScreenConnection);
    lv_obj_set_width(ui_connectionLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_connectionLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_connectionLabel, 0);
    lv_obj_set_y(ui_connectionLabel, 10);
    lv_obj_set_align(ui_connectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectionLabel, "");
    lv_obj_set_style_text_font(ui_connectionLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);


}
