// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_ScreenBoolControl_screen_init(void)
{
    ui_ScreenBoolControl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBoolControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_ScreenBoolControl);
    lv_obj_set_width(ui_Switch1, 145);
    lv_obj_set_height(ui_Switch1, 67);
    lv_obj_set_x(ui_Switch1, -1);
    lv_obj_set_y(ui_Switch1, 14);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_labelBoolControl = lv_label_create(ui_ScreenBoolControl);
    lv_obj_set_width(ui_labelBoolControl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBoolControl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBoolControl, -4);
    lv_obj_set_y(ui_labelBoolControl, -47);
    lv_obj_set_align(ui_labelBoolControl, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_labelBoolControl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelONOFF = lv_label_create(ui_ScreenBoolControl);
    lv_obj_set_width(ui_labelONOFF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelONOFF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelONOFF, 133);
    lv_obj_set_y(ui_labelONOFF, 13);
    lv_obj_set_align(ui_labelONOFF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelONOFF, "OFF");
    lv_obj_set_style_text_font(ui_labelONOFF, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnHome5 = lv_btn_create(ui_ScreenBoolControl);
    lv_obj_set_width(ui_btnHome5, 144);
    lv_obj_set_height(ui_btnHome5, 60);
    lv_obj_set_x(ui_btnHome5, 0);
    lv_obj_set_y(ui_btnHome5, -26);
    lv_obj_set_align(ui_btnHome5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnHome5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnHome5, &ui_img_pulsante_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome5, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnHome5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnHome5, ui_event_btnHome5, LV_EVENT_ALL, NULL);

}
