// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_homeBg = lv_img_create(ui_Screen1);
    lv_obj_set_align(ui_homeBg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_homeBg, 0);
    lv_obj_set_y(ui_homeBg, 0);
    lv_obj_clear_flag(ui_homeBg, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_homeBg, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t *top_band = lv_obj_create(ui_Screen1);
    lv_obj_set_width(top_band, LV_PCT(100));
    lv_obj_set_height(top_band, 30);
    lv_obj_set_x(top_band, 0);
    lv_obj_set_y(top_band, 0);
    lv_obj_set_align(top_band, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(top_band, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(top_band, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(top_band, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(top_band, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(top_band, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(top_band, LV_OPA_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 240);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -260);
    lv_obj_set_y(ui_Button1, -165);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 240);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -260);
    lv_obj_set_y(ui_Button2, -105);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 240);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -260);
    lv_obj_set_y(ui_Button3, -45);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 240);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -260);
    lv_obj_set_y(ui_Button4, 15);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button5, 240);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -260);
    lv_obj_set_y(ui_Button5, 75);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button6 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button6, 240);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -260);
    lv_obj_set_y(ui_Button6, 135);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button7 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button7, 240);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 260);
    lv_obj_set_y(ui_Button7, -165);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button8 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button8, 240);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, 260);
    lv_obj_set_y(ui_Button8, -105);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button9 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button9, 240);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, 260);
    lv_obj_set_y(ui_Button9, -45);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button10 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button10, 240);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 260);
    lv_obj_set_y(ui_Button10, 15);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button11 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button11, 240);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, 260);
    lv_obj_set_y(ui_Button11, 75);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button12 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button12, 240);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, 260);
    lv_obj_set_y(ui_Button12, 135);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    lv_obj_t *main_buttons[] = {
        ui_Button1, ui_Button2, ui_Button3, ui_Button4, ui_Button5, ui_Button6,
        ui_Button7, ui_Button8, ui_Button9, ui_Button10, ui_Button11, ui_Button12};
    for (uint32_t i = 0; i < (sizeof(main_buttons) / sizeof(main_buttons[0])); i++)
    {
        lv_obj_set_style_bg_color(main_buttons[i], lv_color_hex(0x1E3A8A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(main_buttons[i], LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    ui_labelBtn1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn1, -260);
    lv_obj_set_y(ui_labelBtn1, -165);
    lv_obj_set_align(ui_labelBtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn1, "Temp1");
    lv_obj_set_style_text_color(ui_labelBtn1, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn2, -260);
    lv_obj_set_y(ui_labelBtn2, -106);
    lv_obj_set_align(ui_labelBtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn2, "Temp2");
    lv_obj_set_style_text_color(ui_labelBtn2, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn3, -260);
    lv_obj_set_y(ui_labelBtn3, -45);
    lv_obj_set_align(ui_labelBtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn3, "Temp3");
    lv_obj_set_style_text_color(ui_labelBtn3, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn4, -260);
    lv_obj_set_y(ui_labelBtn4, 15);
    lv_obj_set_align(ui_labelBtn4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn4, "Temp4");
    lv_obj_set_style_text_color(ui_labelBtn4, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn5, -260);
    lv_obj_set_y(ui_labelBtn5, 75);
    lv_obj_set_align(ui_labelBtn5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn5, "Temp5");
    lv_obj_set_style_text_color(ui_labelBtn5, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn6, -260);
    lv_obj_set_y(ui_labelBtn6, 135);
    lv_obj_set_align(ui_labelBtn6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn6, "Temp6");
    lv_obj_set_style_text_color(ui_labelBtn6, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn7, 260);
    lv_obj_set_y(ui_labelBtn7, -165);
    lv_obj_set_align(ui_labelBtn7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn7, "Temp7");
    lv_obj_set_style_text_color(ui_labelBtn7, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn8, 260);
    lv_obj_set_y(ui_labelBtn8, -105);
    lv_obj_set_align(ui_labelBtn8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn8, "Temp8");
    lv_obj_set_style_text_color(ui_labelBtn8, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn9, 260);
    lv_obj_set_y(ui_labelBtn9, -45);
    lv_obj_set_align(ui_labelBtn9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn9, "Temp9");
    lv_obj_set_style_text_color(ui_labelBtn9, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn10, 260);
    lv_obj_set_y(ui_labelBtn10, 15);
    lv_obj_set_align(ui_labelBtn10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn10, "Temp10");
    lv_obj_set_style_text_color(ui_labelBtn10, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelBtn11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labelBtn11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labelBtn11, 260);
    lv_obj_set_y(ui_labelBtn11, 75);
    lv_obj_set_align(ui_labelBtn11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn11, "Temp11");
    lv_obj_set_style_text_color(ui_labelBtn11, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeBtn12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labeBtn12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labeBtn12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labeBtn12, 260);
    lv_obj_set_y(ui_labeBtn12, 135);
    lv_obj_set_align(ui_labeBtn12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeBtn12, "Temp12");
    lv_obj_set_style_text_color(ui_labeBtn12, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeBtn12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeBtn12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Temperature labels — right of left-column buttons, left of right-column buttons
    ui_tempLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel1, -60);
    lv_obj_set_y(ui_tempLabel1, -165);
    lv_obj_set_align(ui_tempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel1, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel2, -60);
    lv_obj_set_y(ui_tempLabel2, -105);
    lv_obj_set_align(ui_tempLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel2, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel3, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel3, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel3, -60);
    lv_obj_set_y(ui_tempLabel3, -45);
    lv_obj_set_align(ui_tempLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel3, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel4, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel4, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel4, -60);
    lv_obj_set_y(ui_tempLabel4, 15);
    lv_obj_set_align(ui_tempLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel4, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel5, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel5, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel5, -60);
    lv_obj_set_y(ui_tempLabel5, 75);
    lv_obj_set_align(ui_tempLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel5, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel6, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel6, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel6, -60);
    lv_obj_set_y(ui_tempLabel6, 135);
    lv_obj_set_align(ui_tempLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel6, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel7, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel7, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel7, 60);
    lv_obj_set_y(ui_tempLabel7, -165);
    lv_obj_set_align(ui_tempLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel7, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel8, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel8, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel8, 60);
    lv_obj_set_y(ui_tempLabel8, -105);
    lv_obj_set_align(ui_tempLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel8, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel9, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel9, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel9, 60);
    lv_obj_set_y(ui_tempLabel9, -45);
    lv_obj_set_align(ui_tempLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel9, "25.5\xC2\xB0"
                                     "C");
    lv_obj_set_style_text_color(ui_tempLabel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel10, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel10, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel10, 60);
    lv_obj_set_y(ui_tempLabel10, 15);
    lv_obj_set_align(ui_tempLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel10, "25.5\xC2\xB0"
                                      "C");
    lv_obj_set_style_text_color(ui_tempLabel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel11, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel11, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel11, 60);
    lv_obj_set_y(ui_tempLabel11, 75);
    lv_obj_set_align(ui_tempLabel11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel11, "25.5\xC2\xB0"
                                      "C");
    lv_obj_set_style_text_color(ui_tempLabel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel12, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempLabel12, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempLabel12, 60);
    lv_obj_set_y(ui_tempLabel12, 135);
    lv_obj_set_align(ui_tempLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel12, "25.5\xC2\xB0"
                                      "C");
    lv_obj_set_style_text_color(ui_tempLabel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel12, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

// Round LED indicators for mode-2 buttons (x=±120, same y as each button)
#define LED_SIZE 16
#define LED_RADIUS 8
    lv_obj_t **leds[] = {
        &ui_ledBtn1, &ui_ledBtn2, &ui_ledBtn3, &ui_ledBtn4,
        &ui_ledBtn5, &ui_ledBtn6, &ui_ledBtn7, &ui_ledBtn8,
        &ui_ledBtn9, &ui_ledBtn10, &ui_ledBtn11, &ui_ledBtn12};
    int led_x[] = {-120, -120, -120, -120, -120, -120, 120, 120, 120, 120, 120, 120};
    int led_y[] = {-165, -105, -45, 15, 75, 135, -165, -105, -45, 15, 75, 135};
    for (int i = 0; i < 12; i++)
    {
        *leds[i] = lv_obj_create(ui_Screen1);
        lv_obj_set_size(*leds[i], LED_SIZE, LED_SIZE);
        lv_obj_set_x(*leds[i], led_x[i]);
        lv_obj_set_y(*leds[i], led_y[i]);
        lv_obj_set_align(*leds[i], LV_ALIGN_CENTER);
        lv_obj_set_style_radius(*leds[i], LED_RADIUS, LV_PART_MAIN);
        lv_obj_set_style_border_width(*leds[i], 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(*leds[i], 0, LV_PART_MAIN);
        lv_obj_clear_flag(*leds[i], LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(*leds[i], lv_color_hex(0x00AA00), LV_PART_MAIN);
        lv_obj_add_flag(*leds[i], LV_OBJ_FLAG_HIDDEN);
    }
#undef LED_SIZE
#undef LED_RADIUS

    // Hide temperature labels until valid data arrives from RS485
    lv_obj_add_flag(ui_tempLabel1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel7, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel8, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel9, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel10, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel11, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempLabel12, LV_OBJ_FLAG_HIDDEN);

    ui_btnInfo = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnInfo, 50);
    lv_obj_set_height(ui_btnInfo, 50);
    lv_obj_set_x(ui_btnInfo, 3);
    lv_obj_set_y(ui_btnInfo, 200);
    lv_obj_set_align(ui_btnInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_btnInfo, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_btnInfo, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInfo, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInfo, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *ui_btnInfo_label = lv_label_create(ui_btnInfo);
    lv_label_set_text(ui_btnInfo_label, "i");
    lv_obj_set_style_text_font(ui_btnInfo_label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnInfo_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(ui_btnInfo_label);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_Label2, 50); // visualizza id del display
    lv_obj_set_y(ui_Label2, 10);
    lv_label_set_text(ui_Label2, "id:-----");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    ui_btnPrevPage = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnPrevPage, 100);
    lv_obj_set_height(ui_btnPrevPage, 50);
    lv_obj_set_x(ui_btnPrevPage, -330);
    lv_obj_set_y(ui_btnPrevPage, 200);
    lv_obj_set_align(ui_btnPrevPage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPrevPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_btnPrevPage, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_btnPrevPage, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPrevPage, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnPrevPage, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnPrevPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnPrevPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnPrevPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *ui_btnPrevPage_label = lv_label_create(ui_btnPrevPage);
    lv_label_set_text(ui_btnPrevPage_label, "<");
    lv_obj_set_style_text_font(ui_btnPrevPage_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnPrevPage_label, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(ui_btnPrevPage_label);

    ui_btnNextPage = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnNextPage, 100);
    lv_obj_set_height(ui_btnNextPage, 50);
    lv_obj_set_x(ui_btnNextPage, 330);
    lv_obj_set_y(ui_btnNextPage, 200);
    lv_obj_set_align(ui_btnNextPage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnNextPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_btnNextPage, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_btnNextPage, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnNextPage, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnNextPage, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnNextPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnNextPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnNextPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *ui_btnNextPage_label = lv_label_create(ui_btnNextPage);
    lv_label_set_text(ui_btnNextPage_label, ">");
    lv_obj_set_style_text_font(ui_btnNextPage_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnNextPage_label, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(ui_btnNextPage_label);

    ui_labelPageNum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelPageNum, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_labelPageNum, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_labelPageNum, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_x(ui_labelPageNum, -8);
    lv_obj_set_y(ui_labelPageNum, 6);
    lv_label_set_text(ui_labelPageNum, "0/0");
    lv_obj_set_style_text_color(ui_labelPageNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPageNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPageNum, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnInfo, ui_event_btnInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPrevPage, ui_event_btnPrevPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnNextPage, ui_event_btnNextPage, LV_EVENT_ALL, NULL);
}
