// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_ScreenView_screen_init(void)
{
    ui_ScreenView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnHome4 = lv_btn_create(ui_ScreenView);
    lv_obj_set_width(ui_btnHome4, 144);
    lv_obj_set_height(ui_btnHome4, 60);
    lv_obj_set_x(ui_btnHome4, -1);
    lv_obj_set_y(ui_btnHome4, -26);
    lv_obj_set_align(ui_btnHome4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnHome4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnHome4, &ui_img_pulsante_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome4, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnHome4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewTempValue = lv_label_create(ui_ScreenView);
    lv_obj_set_width(ui_viewTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_viewTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_viewTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_viewTempValue, "--");
    lv_obj_set_style_text_font(ui_viewTempValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelViewTemp = lv_label_create(ui_ScreenView);
    lv_obj_set_width(ui_labelViewTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelViewTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelViewTemp, -2);
    lv_obj_set_y(ui_labelViewTemp, 79);
    lv_obj_set_align(ui_labelViewTemp, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_font(ui_labelViewTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugLabel1 = lv_label_create(ui_ScreenView);
    lv_obj_set_width(ui_debugLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debugLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_debugLabel1, LV_ALIGN_TOP_RIGHT);

    lv_obj_add_event_cb(ui_btnHome4, ui_event_btnHome4, LV_EVENT_ALL, NULL);

}
