// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_ScreenSetting_screen_init(void)
{
    ui_ScreenSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingBg = lv_img_create(ui_ScreenSetting);
    lv_obj_set_align(ui_settingBg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_settingBg, 0);
    lv_obj_set_y(ui_settingBg, 0);
    lv_obj_clear_flag(ui_settingBg, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_settingBg, LV_OBJ_FLAG_HIDDEN);

    ui_btnHome1 = lv_btn_create(ui_ScreenSetting);
    lv_obj_set_width(ui_btnHome1, 144);
    lv_obj_set_height(ui_btnHome1, 60);
    lv_obj_set_x(ui_btnHome1, -1);
    lv_obj_set_y(ui_btnHome1, -26);
    lv_obj_set_align(ui_btnHome1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnHome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnHome1, &ui_img_pulsante_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome1, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnHome1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_ScreenSetting);
    lv_obj_set_width(ui_Arc1, 254);
    lv_obj_set_height(ui_Arc1, 254);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, -1);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 300);
    lv_arc_set_value(ui_Arc1, 12);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x1E3A8A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x1E3A8A), LV_PART_KNOB | LV_STATE_DEFAULT);


    ui_setPointNum = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_setPointNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setPointNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_setPointNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setPointNum, "--");
    lv_obj_set_style_text_font(ui_setPointNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_regLabel = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_regLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_regLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_regLabel, -2);
    lv_obj_set_y(ui_regLabel, 79);
    lv_obj_set_align(ui_regLabel, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_font(ui_regLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_regLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_regLabel, LV_OPA_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_regLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_regLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_regLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_regLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_regLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempInPage = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_tempInPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempInPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempInPage, 81);
    lv_obj_set_y(ui_tempInPage, 218);
    lv_label_set_text(ui_tempInPage, "--");
    lv_obj_set_style_text_font(ui_tempInPage, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTempInPage = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_labelTempInPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTempInPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTempInPage, -250);
    lv_obj_set_y(ui_labelTempInPage, -55);
    lv_obj_set_align(ui_labelTempInPage, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_labelTempInPage, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelTempInPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelTempInPage, LV_OPA_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelTempInPage, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelTempInPage, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelTempInPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelTempInPage, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_labelTempInPage, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugLabel = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_debugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debugLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_debugLabel, LV_ALIGN_TOP_RIGHT);

    lv_obj_add_event_cb(ui_btnHome1, ui_event_btnHome1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);

}
