// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button14, 240);
    lv_obj_set_height(ui_Button14, 50);
    lv_obj_set_x(ui_Button14, -260);
    lv_obj_set_y(ui_Button14, -180);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button15, 240);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, -260);
    lv_obj_set_y(ui_Button15, -120);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button16, 240);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_x(ui_Button16, -260);
    lv_obj_set_y(ui_Button16, -60);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button17 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button17, 240);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, -260);
    lv_obj_set_y(ui_Button17, 0);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button18 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button18, 240);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_x(ui_Button18, -260);
    lv_obj_set_y(ui_Button18, 60);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button19 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button19, 240);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, -260);
    lv_obj_set_y(ui_Button19, 120);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button20 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button20, 240);
    lv_obj_set_height(ui_Button20, 50);
    lv_obj_set_x(ui_Button20, 260);
    lv_obj_set_y(ui_Button20, -180);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button21 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button21, 240);
    lv_obj_set_height(ui_Button21, 50);
    lv_obj_set_x(ui_Button21, 260);
    lv_obj_set_y(ui_Button21, -120);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button22 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button22, 240);
    lv_obj_set_height(ui_Button22, 50);
    lv_obj_set_x(ui_Button22, 260);
    lv_obj_set_y(ui_Button22, -60);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button23 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button23, 240);
    lv_obj_set_height(ui_Button23, 50);
    lv_obj_set_x(ui_Button23, 260);
    lv_obj_set_y(ui_Button23, 0);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button24 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button24, 240);
    lv_obj_set_height(ui_Button24, 50);
    lv_obj_set_x(ui_Button24, 260);
    lv_obj_set_y(ui_Button24, 60);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button25 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button25, 240);
    lv_obj_set_height(ui_Button25, 50);
    lv_obj_set_x(ui_Button25, 260);
    lv_obj_set_y(ui_Button25, 120);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelBtn12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn12, -260);
    lv_obj_set_y(ui_labelBtn12, -180);
    lv_obj_set_align(ui_labelBtn12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn12, "Temp1");
    lv_obj_set_style_text_color(ui_labelBtn12, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn13, -260);
    lv_obj_set_y(ui_labelBtn13, -121);
    lv_obj_set_align(ui_labelBtn13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn13, "Temp2");
    lv_obj_set_style_text_color(ui_labelBtn13, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn14, -260);
    lv_obj_set_y(ui_labelBtn14, -60);
    lv_obj_set_align(ui_labelBtn14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn14, "Temp3");
    lv_obj_set_style_text_color(ui_labelBtn14, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn15 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn15, -260);
    lv_obj_set_y(ui_labelBtn15, 0);
    lv_obj_set_align(ui_labelBtn15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn15, "Temp4");
    lv_obj_set_style_text_color(ui_labelBtn15, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn16, -260);
    lv_obj_set_y(ui_labelBtn16, 60);
    lv_obj_set_align(ui_labelBtn16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn16, "Temp5");
    lv_obj_set_style_text_color(ui_labelBtn16, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn17, -260);
    lv_obj_set_y(ui_labelBtn17, 120);
    lv_obj_set_align(ui_labelBtn17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn17, "Temp6");
    lv_obj_set_style_text_color(ui_labelBtn17, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn17, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn18 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn18, 260);
    lv_obj_set_y(ui_labelBtn18, -180);
    lv_obj_set_align(ui_labelBtn18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn18, "Temp7");
    lv_obj_set_style_text_color(ui_labelBtn18, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn18, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn19 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn19, 260);
    lv_obj_set_y(ui_labelBtn19, -120);
    lv_obj_set_align(ui_labelBtn19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn19, "Temp8");
    lv_obj_set_style_text_color(ui_labelBtn19, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn19, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn20 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn20, 260);
    lv_obj_set_y(ui_labelBtn20, -60);
    lv_obj_set_align(ui_labelBtn20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn20, "Temp9");
    lv_obj_set_style_text_color(ui_labelBtn20, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn20, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn21 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn21, 260);
    lv_obj_set_y(ui_labelBtn21, 0);
    lv_obj_set_align(ui_labelBtn21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn21, "Temp10");
    lv_obj_set_style_text_color(ui_labelBtn21, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBtn22 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelBtn22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBtn22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBtn22, 260);
    lv_obj_set_y(ui_labelBtn22, 60);
    lv_obj_set_align(ui_labelBtn22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBtn22, "Temp11");
    lv_obj_set_style_text_color(ui_labelBtn22, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBtn22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBtn22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeBtn1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labeBtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeBtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeBtn1, 260);
    lv_obj_set_y(ui_labeBtn1, 120);
    lv_obj_set_align(ui_labeBtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeBtn1, "Temp12");
    lv_obj_set_style_text_color(ui_labeBtn1, lv_color_hex(0xF4F5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeBtn1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnInfo1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_btnInfo1, 100);
    lv_obj_set_height(ui_btnInfo1, 50);
    lv_obj_set_x(ui_btnInfo1, 3);
    lv_obj_set_y(ui_btnInfo1, 200);
    lv_obj_set_align(ui_btnInfo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnInfo1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnInfo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnInfo1, &ui_img_btn_info_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "-----");

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnInfo1, ui_event_btnInfo1, LV_EVENT_ALL, NULL);

}
