// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BLU 0
#define UI_THEME_COLOR_ARANCIO 1
#define UI_THEME_COLOR_NERO 2
#define UI_THEME_COLOR_VERDE 3
#define UI_THEME_COLOR_GRIGIO_SFONDO 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_TERMOSTATO 1

extern const ui_theme_variable_t _ui_theme_color_Blu[2];
extern const ui_theme_variable_t _ui_theme_alpha_Blu[2];

extern const ui_theme_variable_t _ui_theme_color_Arancio[2];
extern const ui_theme_variable_t _ui_theme_alpha_Arancio[2];

extern const ui_theme_variable_t _ui_theme_color_nero[2];
extern const ui_theme_variable_t _ui_theme_alpha_nero[2];

extern const ui_theme_variable_t _ui_theme_color_verde[2];
extern const ui_theme_variable_t _ui_theme_alpha_verde[2];

extern const ui_theme_variable_t _ui_theme_color_grigio_sfondo[2];
extern const ui_theme_variable_t _ui_theme_alpha_grigio_sfondo[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
