// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Solaria basic app

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Blu[2] = {0x389FE1, 0x389FE1};
const ui_theme_variable_t _ui_theme_alpha_Blu[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Arancio[2] = {0xFFA426, 0xFFA426};
const ui_theme_variable_t _ui_theme_alpha_Arancio[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_nero[2] = {0x3D3D3D, 0x3D3D3D};
const ui_theme_variable_t _ui_theme_alpha_nero[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_verde[2] = {0x21AC8F, 0x21AC8F};
const ui_theme_variable_t _ui_theme_alpha_verde[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_grigio_sfondo[2] = {0xF4F6F5, 0xF4F6F5};
const ui_theme_variable_t _ui_theme_alpha_grigio_sfondo[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_TERMOSTATO;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

